#!/bin/sh
export PATH="/run/current-system/sw/bin:$PATH"
card=$(grep -rl "1002:747E" /sys/class/drm/card*/device/uevent 2>/dev/null | grep -o 'card[0-9]*' | head -1)
usage=$(cat /sys/class/drm/${card:-card1}/device/gpu_busy_percent 2>/dev/null || echo 0)
echo "{\"text\": \"${usage}%\", \"tooltip\": \"GPU Usage: ${usage}%\"}"
