# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-9491d3c1-8605-472f-86fe-8ee6dd6b129d";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-9491d3c1-8605-472f-86fe-8ee6dd6b129d".device = "/dev/disk/by-uuid/9491d3c1-8605-472f-86fe-8ee6dd6b129d";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C9FB-8B28";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-9e3a9bbb-dc4d-4ada-9d02-a6770bc704d0"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
